CREATE DATABASE ADE_Academico;
CREATE DATABASE ADE_Estudiantes;
CREATE DATABASE ADE_Docentes;
CREATE DATABASE ADE_Matriculas;
CREATE DATABASE ADE_Calificaciones;
CREATE DATABASE ADE_Finanzas;
CREATE DATABASE ADE_Seguridad;
CREATE DATABASE ADE_Notificaciones;
