<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="*" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ADE.Notificaciones.Domain\ADE.Notificaciones.Domain.csproj" />
  </ItemGroup>

</Project>
